import React, { useEffect, useState } from "react";
import { getAllPosts } from "../api/admin";
import { useRouter } from "next/router";
import Loader from "../../components/Loader";
import Head from "next/head";
import BlogCard from "../../components/BlogCard";
import { Post } from "../../types/post";
import Header from "../../components/Header";
import { motion } from "framer-motion";
import Link from "next/link";
const container = {
  hidden: { opacity: 1, scale: 0 },
  visible: {
    opacity: 1,
    scale: 1,
    transition: {
      delayChildren: 0.3,
      staggerChildren: 0.2,
    },
  },
};

interface PostData {
  posts: Post[];
  nBits: number;
}

function Index() {
  const router = useRouter();
  const [isLoading, setLoading] = useState(true);
  const [postData, setPostData] = useState<PostData | null>();
  useEffect(() => {
    (async () => {
      const data = await getAllPosts();
      console.log(data);
      setPostData(data);
      setLoading(false);
    })();
  }, []);

  return (
    <div className="w-full flex flex-col justify-center items-center min-h-[100vh]">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full flex flex-col gap-2 items-center pb-10 px-2">
        {isLoading ? (
          <Loader />
        ) : (
          <>
            <Header />
            <div className="flex w-full justify-end px-4">
              <Link
                href="/admin/newpost"
                className=" px-4 py-2 font-bold rounded shadow focus:outline-none focus:ring hover:ring focus:ring-opacity-50 bg-[#980000] focus:ring-[#980000] hover:ring-[#980000] text-gray-50"
              >
                Add New Post
              </Link>
            </div>
            {postData &&
              postData?.posts.map((post: Post, index) => (
                <BlogCard key={post._id} {...post} link={`/posts/${post._id}`} index={index} />
              ))}
          </>
        )}
      </div>
    </div>
  );
}

export default Index;
