import React, { useEffect, useState } from "react";
import { getAllPosts } from "../api/admin";
import { useRouter } from "next/router";
import Loader from "../../components/Loader";
import Head from "next/head";
import BlogCard from "../../components/BlogCard";
import { Post } from "../../types/post";
import Header from "../../components/Header";
import { motion } from "framer-motion";
import Link from "next/link";
import { justify } from "@cloudinary/url-gen/qualifiers/textAlignment";
const container = {
  hidden: { opacity: 1, scale: 0 },
  visible: {
    opacity: 1,
    scale: 1,
    transition: {
      delayChildren: 0.3,
      staggerChildren: 0.2,
    },
  },
};

interface PostData {
  posts: Post[];
  nBits: number;
}

function Index() {
  const router = useRouter();
  const [isLoading, setLoading] = useState(true);
  const [postData, setPostData] = useState<PostData | null>();
  const [pub, setPub] = useState<boolean>(false);
  useEffect(() => {
    (async () => {
      const data = await getAllPosts();
      // console.log(data);
      setPostData(data);
      setLoading(false);
    })();
  }, []);

  return (
    <div className="w-full flex flex-col  items-center min-h-[100vh]">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
        {/* <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin={true}> */}
        <link
          href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@100;200;300;400&family=Noto+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;1,100;1,200;1,300;1,400;1,500;1,600;1,800;1,900&family=PT+Serif:ital,wght@0,400;0,700;1,400;1,700&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,700;1,900&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <div className="w-full flex flex-col gap-2 items-center pb-10 px-2">
        <Header />
        {isLoading ? (
          <Loader />
        ) : (
          <>
            <div className="flex w-full justify-end px-4">
              <Link
                href="/admin/newpost"
                className=" px-4 py-2 font-bold rounded shadow focus:outline-none focus:ring hover:ring focus:ring-opacity-50 bg-[#980000] focus:ring-[#980000] hover:ring-[#980000] text-gray-50"
              >
                Add New Post
              </Link>
            </div>
            <div className="flex w-full justify-center gap-2 px-4">
              <button
                onClick={() => {
                  setPub(true);
                }}
                className={` px-4 py-2 font-bold rounded shadow focus:outline-none focus:ring hover:ring focus:ring-opacity-50   ${
                  pub && "bg-[#980000] ring-[#f82222] hover:ring-[#980000] text-gray-50"
                } `}
              >
                Published Posts
              </button>
              <button
                onClick={() => {
                  setPub(false);
                }}
                className={` px-4 py-2 font-bold rounded shadow focus:outline-none focus:ring hover:ring focus:ring-opacity-50  ${
                  !pub && "bg-[#980000] ring-[#f82222] hover:ring-[#980000] text-gray-50"
                } `}
              >
                Unpublished Posts
              </button>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-2 w-full px-2">
              {postData &&
                postData?.posts
                  .filter((obj) => {
                    if (pub) {
                      return obj.isPublished;
                    } else {
                      return !obj.isPublished;
                    }
                  })
                  .map((post: Post, index) => (
                    <BlogCard key={post._id} {...post} link={`/posts/${post._id}`} index={index} />
                  ))}
            </div>
          </>
        )}
      </div>
    </div>
  );
}

export default Index;
