import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import "../axios";
import axios from "axios";
import { Post } from "../types/post";
import Link from "next/link";
import { useState, useEffect } from "react";
import { useRouter } from "next/router";
import BlogCard from "../components/BlogCard";
import Pagination from "../components/Pagination";
import Header from "../components/Header";
import { getPublishedPosts } from "./api/posts.js";
import { useAuthContext } from "../contexts/authContext";

export default function Home({ pageData }) {
  // console.log(page);
  const router = useRouter();
  const { setToken } = useAuthContext();
  useEffect(() => {
    let token = localStorage.getItem("token");
    if (token) {
      token = JSON.parse(token);
      setToken("token");
    }
  }, []);
  return (
    <div className={`flex flex-col items-center`}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="w-full grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-2  py-10 px-10">
        {pageData.posts.map((post: Post, index) => (
          <BlogCard key={post._id} {...post} link={`/posts/${post._id}`} index={index} />
        ))}
      </div>
      <div className="w-full flex justify-center py-2 items-center">
        <Pagination totalPages={pageData.totalPages} currentPage={pageData.page} />
      </div>
    </div>
  );
}

export async function getServerSideProps(context: any) {
  const pageData = await getPublishedPosts(context.query.page || 1);
  return {
    props: {
      pageData,
    },
  };
}
