import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import "../axios";
import axios from "axios";
import { Post } from "../types/post";
import Link from "next/link";
import { useState } from "react";
import { useRouter } from "next/router";
import BlogCard from "../components/BlogCard";
import Pagination from "../components/Pagination";
import Header from "../components/Header";
import { getPublishedPosts } from "./api/posts.js";

export default function Home({ pageData }) {
  // console.log(page);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="flex flex-col gap-2 items-center py-10 px-2">
        {pageData.posts.map((post: Post) => (
          <BlogCard key={post._id} {...post} />
        ))}
        <Pagination totalPages={pageData.totalPages} currentPage={pageData.page} />
      </div>
    </div>
  );
}

export async function getServerSideProps(context: any) {
  const pageData = await getPublishedPosts(context.query.page || 1);
  return {
    props: {
      pageData,
    },
  };
}
